import { Ticket } from "./type";

export const tickets: Ticket[] = [
  {
    id: "TCKT001",
    subject: "Internet Connectivity Issue",
    description: "Users are experiencing intermittent internet connectivity.",
    category: "IT Support",
    subCategory: "Network Issues",
    created_on: new Date("2024-07-01"),
    created_by: "John Doe",
    created_by_img: "https://example.com/johndoe.jpg",
    assigned_to: "Jane Smith",
    assigned_to_img: "https://example.com/janesmith.jpg",
    status: "ongoing",
  },
  {
    id: "TCKT002",
    subject: "Software Installation Problem",
    description: "Unable to install the latest version of software X.",
    category: "IT Support",
    subCategory: "Software Issues",
    created_on: new Date("2024-06-30"),
    created_by: "Alice Johnson",
    created_by_img: "https://example.com/alicejohnson.jpg",
    assigned_to: "Bob Brown",
    assigned_to_img: "https://example.com/bobbrown.jpg",
    status: "created",
  },
  {
    id: "TCKT003",
    subject: "Printer Not Printing",
    description: "Printer is not responding when trying to print documents.",
    category: "Hardware Support",
    subCategory: "Printer Issues",
    created_on: new Date("2024-07-02"),
    created_by: "Emily Davis",
    created_by_img: "https://example.com/emilydavis.jpg",
    assigned_to: "Chris Wilson",
    assigned_to_img: "https://example.com/chriswilson.jpg",
    status: "created",
  },
  {
    id: "TCKT004",
    subject: "Email Delivery Delay",
    description:
      "Outgoing emails are delayed and not reaching recipients promptly.",
    category: "Email Support",
    subCategory: "Delivery Issues",
    created_on: new Date("2024-07-03"),
    created_by: "Michael Lee",
    created_by_img: "https://example.com/michaellee.jpg",
    assigned_to: "Sarah Adams",
    assigned_to_img: "https://example.com/sarahadams.jpg",
    status: "not-resolved",
  },
  {
    id: "TCKT005",
    subject: "Data Backup Failure",
    description: "Scheduled data backups are failing unexpectedly.",
    category: "IT Support",
    subCategory: "Data Backup",
    created_on: new Date("2024-06-29"),
    created_by: "Andrew Wilson",
    created_by_img: "https://example.com/andrewwilson.jpg",
    assigned_to: "Emma Brown",
    assigned_to_img: "https://example.com/emmabrown.jpg",
    status: "resolved",
  },
  {
    id: "TCKT006",
    subject: "Server Performance Degradation",
    description: "Server X is experiencing slow performance during peak hours.",
    category: "IT Support",
    subCategory: "Server Issues",
    created_on: new Date("2024-06-28"),
    created_by: "Sophia Martinez",
    created_by_img: "https://example.com/sophiamartinez.jpg",
    assigned_to: "David Clark",
    assigned_to_img: "https://example.com/davidclark.jpg",
    status: "ongoing",
  },
  {
    id: "TCKT007",
    subject: "Password Reset Request",
    description: "User needs assistance with resetting their account password.",
    category: "Account Support",
    subCategory: "Password Reset",
    created_on: new Date("2024-06-27"),
    created_by: "Olivia Taylor",
    created_by_img: "https://example.com/oliviataylor.jpg",
    assigned_to: "Jason Green",
    assigned_to_img: "https://example.com/jasongreen.jpg",
    status: "created",
  },
  {
    id: "TCKT008",
    subject: "Software Bug Report",
    description: "Found a critical bug in software Y that causes crashes.",
    category: "Software Development",
    subCategory: "Bug Report",
    created_on: new Date("2024-07-04"),
    created_by: "Daniel Wilson",
    created_by_img: "https://example.com/danielwilson.jpg",
    assigned_to: "Isabella Brown",
    assigned_to_img: "https://example.com/isabellabrown.jpg",
    status: "created",
  },
  {
    id: "TCKT009",
    subject: "Website Downtime",
    description: "Website is currently down and inaccessible to users.",
    category: "Web Support",
    subCategory: "Downtime Issues",
    created_on: new Date("2024-07-03"),
    created_by: "James Anderson",
    created_by_img: "https://example.com/jamesanderson.jpg",
    assigned_to: "Sophie Roberts",
    assigned_to_img: "https://example.com/sophieroberts.jpg",
    status: "not-resolved",
  },
  {
    id: "TCKT010",
    subject: "Database Connection Error",
    description: "Unable to establish connection to the main database server.",
    category: "IT Support",
    subCategory: "Database Issues",
    created_on: new Date("2024-07-02"),
    created_by: "Mia Moore",
    created_by_img: "https://example.com/miamoore.jpg",
    assigned_to: "William Thompson",
    assigned_to_img: "https://example.com/williamthompson.jpg",
    status: "resolved",
  },
];
